#!/bin/bash

# Help.sh — Print usage and documentation for the DTI processing pipeline

echo ""
echo "========================== DTI + SC Processing Pipeline Help =========================="
echo ""
echo "Usage:"
echo "  singularity run combined_pipeline.sif -s <Subject_Name> -i <T1_Image> -d <DWI_Image> -o <Output_Path> -z <Denoise_Mode> -e <Distortion_Correction_Mode> -B <Pipeline_Mode> [options]"
echo ""
echo "Mandatory Arguments:"
echo "  -s   Subject Name"
echo "  -i   T1 Image path (NIfTI format: .nii or .nii.gz)"
echo "  -d   DWI Image path (NIfTI format)"
echo "  -o   Output path (must already exist)"
echo "  -z   Denoise mode:"
echo "         0 - No denoise"
echo "         1 - MPPCA only"
echo "         2 - Gibbs de-ringing + MPPCA (recommended)"
echo "  -e   Distortion correction mode:"
echo "         0 - No correction"
echo "         1 - TOPUP (requires reverse PE image)"
echo "         2 - synb0-disco"
echo "  -B   Pipeline mode:"
echo "         1 - DTI Preprocess and Fernet (DWI only)"
echo "         2 - For non-human models"
echo "         3 - Full DTI pipeline"
echo "         4 - Full DTI pipeline + Structural Connectivity pipeline"
echo "         5 - Animal models (includes modes 1 & 2 + Structural Connectivity)"
echo ""
echo "Optional Arguments:"
echo "  -t   Reverse PE Image path (only if using -e 1)"
echo "  -p   Phase Encoding Direction (e.g., AP, PA, LR, RL, IS, SI)"
echo "  -T   Readout Time (e.g., 0.064 — required for TOPUP)"
echo "  -F   Set to 'True' to run Freesurfer (required for modes 4 and 5)"
echo "  -j   External BrainMaGe mask path (optional)"
echo "  -c   Custom DTI Preprocess mask path (optional)"
echo ""
echo "Example (with reverse PE scan):"
echo "  singularity run combined_pipeline.sif -s sub01 -i T1.nii.gz -d DWI.nii.gz -t revPE.nii.gz -p AP -T 0.064 -o /output -z 2 -e 1 -B 3"
echo ""
echo "Example (without reverse PE scan):"
echo "  singularity run combined_pipeline.sif -s sub01 -i T1.nii.gz -d DWI.nii.gz -o /output -z 2 -e 2 -B 3"
echo ""
echo "Note:"
echo "  - Ensure Singularity (or Apptainer) is installed on your system."
echo "  - The container file (.sif) must be executable: chmod +x combined_pipeline.sif"
echo ""
echo "==================================================================================="
echo ""
exit 0

